_wandb:
    value:
        cli_version: 0.21.3
        e:
            ph1l6dj2uy209yum1i6g8cuhsco9qv91:
                args:
                    - --config
                    - configs/train_highperf.yaml
                    - --mode
                    - full-pipeline
                    - --use-calibration
                    - --auto-continue
                codePath: src/training/train_main.py
                codePathLocal: src/training/train_main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1081101176832"
                        used: "171911204864"
                email: ieyeppo.job@gmail.com
                executable: /home/ieyeppo/.pyenv/versions/cv_py3_11_9/bin/python
                git:
                    commit: 62ace7dc3372867ce56d691d7370e08850c7732c
                    remote: git@github.com:iejob/computer-vision-competition-1SEN.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-b2b9e31d-4ca9-4907-d713-96771c28a1dd
                host: PotG
                memory:
                    total: "42058571776"
                os: Linux-6.6.87.1-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/ieyeppo/AI_Lab/computer-vision-competition-1SEN/src/training/train_main.py
                python: CPython 3.11.9
                root: /home/ieyeppo/AI_Lab/computer-vision-competition-1SEN
                startedAt: "2025-09-10T09:39:47.053749Z"
                writerId: ph1l6dj2uy209yum1i6g8cuhsco9qv91
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
                - 80
                - 105
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
                - 80
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.11.9
            "5": 0.21.3
            "10":
                - 20
            "12": 0.21.3
            "13": linux-x86_64
architecture:
    value: swin_base_384
batch_size:
    value: 72
dataset:
    value: Document Classification
epochs:
    value: 80
framework:
    value: PyTorch
hard_augmentation:
    value: true
image_size:
    value: 384
learning_rate:
    value: 0.0001
mixup_alpha:
    value: 0.8
optimizer:
    value: adamw
scheduler:
    value: cosine
