# ----------------------------- 고성능 추론 메타 설정 ----------------------------- #
project:
  run_name: swin-ensemble-inference                   # 실행(run) 이름 (고성능 앙상블 추론)
  device: "cuda"                                      # 실행 디바이스 ("cuda" 가능 시 GPU, 아니면 CPU)
  num_workers: 4                                      # DataLoader 병렬 로딩 워커 수
  date_format: "%Y%m%d"                               # 날짜 포맷 (예: 20250904)
  time_format: "%H%M"                                 # 시간 포맷 (예: 1530)

# ------------------------------ 앙상블 설정 (고성능용) --------------------------- #
ensemble:
  fold_results_path: "../../experiments/train/20250907/swin-sighperf/fold_results.yaml"  # 앙상블용 폴드 결과
  use_tta: true                                       # Test-Time Augmentation 사용 (고성능)
  num_tta: 5                                          # TTA 횟수 (5회 반복으로 정확도 향상)

# ------------------------------- 데이터 설정 ------------------------------ #
data:
  sample_csv: "../data/raw/sample_submission.csv"     # 제출용 샘플 CSV 경로
  image_dir_test: "../data/raw/test"                  # 추론 대상 테스트 이미지 디렉토리
  image_ext: ".jpg"                                   # 이미지 확장자 (jpg 기본)
  id_col: "ID"                                        # ID 컬럼명
  target_col: "target"                                # 타깃 컬럼명
  num_classes: 17                                     # 분류 클래스 수

# ------------------------------- 모델 설정 (Swin Transformer) -------------------------------- #
model:
  name: "swin_base_384"                               # 모델 아키텍처 이름 (Swin Transformer)
  pretrained: False                                   # 사전학습 가중치 사용 여부 (False → 학습된 가중치 사용)
  drop_rate: 0.1                                      # dropout 비율 (학습시와 동일)
  drop_path_rate: 0.1                                 # stochastic depth 비율 (학습시와 동일)
  pooling: "avg"                                      # 전역 풀링 방식 ("avg" 권장)

# ------------------------- 추론 시 필요한 학습 설정 (고성능) ------------------------- #
train:
  img_size: 384                                       # 학습 때 쓴 값과 동일해야 함 (Swin Transformer 최적 크기)
  batch_size: 32                                      # 고성능 추론용 배치 크기 (메모리 사용량 고려)

# ------------------------------ 고성능 추론/제출 설정 ---------------------------- #
inference:
  tta: true                                           # Test-Time Augmentation 사용 여부
  tta_rot_degrees: [0, -3, 3]                         # TTA 시 회전 각도 리스트
  confidence_threshold: 0.9                           # 앙상블 신뢰도 임계값
  # out_csv 제거: 동적으로 날짜_모델명_ensemble_tta 형식으로 생성

# ------------------------------- 출력/저장 설정 ---------------------------- #
output:
  logs_dir: "logs/infer"                              # 추론 로그 저장 디렉토리
  exp_dir: "../experiments/train"                     # 실험 결과 저장 루트 디렉토리
  snapshots: true                                     # 실행 시 config 스냅샷 저장 여부

# ------------------------------- WandB 설정 (선택적) ---------------------------- #
wandb:
  project_name: document-classification-inference     # WandB 프로젝트명 (고성능 추론용)
  entity: null                                        # WandB 엔티티 (팀/사용자)
  experiment_name: swin-ensemble-inference            # 실험명
  tags:                                               # 실험 태그
  - swin                                              # Swin Transformer 태그
  - ensemble                                          # 앙상블 태그
  - tta                                               # TTA 태그
  - high-performance                                  # 고성능 태그
  enabled: false                                      # 추론시 WandB 비활성화 (기본값)
