project:
  run_name: v094-swin-highperf
  seed: 42
  date_format: '%Y%m%d'
  time_format: '%H%M'
  num_workers: 4
  device: cuda
  verbose: true
  log_prefix: train_highperf
data:
  root: ../data
  train_csv: ../data/raw/train.csv
  sample_csv: ../data/raw/sample_submission.csv
  image_dir_train: ../data/raw/train
  image_dir_test: ../data/raw/test
  image_ext: .jpg
  id_col: ID
  target_col: target
  num_classes: 17
  folds: 5
  valid_fold: all
  stratify: true
train:
  img_size: 384
  batch_size: 32
  epochs: 15
  lr: 0.0001
  weight_decay: 0.01
  optimizer: adamw
  scheduler: cosine
  mixed_precision: true
  max_grad_norm: 1.0
  label_smoothing: 0.1
  use_mixup: true
  mixup_alpha: 1.0
  hard_augmentation: true
  log_interval: 50
model:
  name: swin_base_384
  pretrained: true
  drop_rate: 0.1
  drop_path_rate: 0.1
  pooling: avg
output:
  log_dir: logs/train
  exp_dir: experiments/train
  snapshots: true
wandb:
  project_name: document-classification-team
  entity: null
  experiment_name: swin-highperf
  tags:
  - swin
  - high-performance
  - mixup
  - hard-aug
training:
  batch_size: 48
