# ----------------------------- 빠른 최적화 설정 ----------------------------- #
# 목표: 30분-1시간 내 결과 도출, 높은 성능 유지
project:
  run_name: swin-fast-opt                       # 실행명 (빠른 최적화)
  seed: 42                                      # 랜덤 시드 (재현 가능한 실험)
  date_format: '%Y%m%d'                         # 날짜 포맷 (예: 20250906)
  time_format: '%H%M'                           # 시간 포맷 (예: 1430)
  num_workers: 2                                # 데이터 로더 워커 수 (메모리 최적화)
  device: cuda                                  # 학습 디바이스 (GPU 사용)
  verbose: true                                 # 상세 로그 출력 여부
  log_prefix: train_fast_opt                    # 로그 파일 접두사

# ------------------------------- 데이터 설정 ------------------------------- #
data:
  root: ./data                                  # 데이터 루트 디렉토리
  train_csv: ./data/raw/train.csv               # 학습 데이터 CSV 파일
  sample_csv: ./data/raw/sample_submission.csv  # 제출 샘플 CSV
  image_dir_train: ./data/raw/train             # 학습 이미지 디렉토리
  image_dir_test: ./data/raw/test               # 테스트 이미지 디렉토리
  image_ext: .jpg                               # 이미지 파일 확장자
  id_col: ID                                    # ID 컬럼명
  target_col: target                            # 타겟 컬럼명
  num_classes: 17                               # 클래스 수 (0~16)
  folds: 2                                      # K-폴드 개수 (30분 완료용)
  valid_fold: all                               # 검증 폴드 (전체 폴드 학습)

# ------------------------------- 학습 설정 ------------------------------- #
train:
  img_size: 320                                 # 이미지 크기 (메모리 최적화)
  batch_size: 32                                # 배치 크기 (메모리 최적화)
  use_advanced_augmentation: true               # 기본 증강으로 더 빠른 처리
  epochs: 1                                     # 학습 에포크 수 (30분 완료용)
  lr: 0.0002                                    # 학습률 (조금 높게 설정)
  weight_decay: 0.01                            # L2 정규화 계수
  optimizer: adamw                              # 옵티마이저 (AdamW)
  scheduler: cosine                             # 스케줄러 (코사인 감쇠)
  mixed_precision: true                         # 혼합 정밀도 학습 (메모리 효율성)
  max_grad_norm: 1.0                            # 그래디언트 클리핑 임계값
  label_smoothing: 0.1                          # 레이블 스무딩 (과적합 방지)
  use_mixup: true                               # Mixup 데이터 증강 사용
  mixup_alpha: 0.8                              # Mixup 알파 파라미터 (조금 낮게)
  hard_augmentation: false                      # 강한 데이터 증강 비활성화 (빠른 처리)
  log_interval: 5                               # 로그 출력 간격 (더 자주 출력)

# ------------------------------- 모델 설정 ------------------------------- #
model:
  name: swin_base_384                           # 모델 아키텍처 (지원되는 모델로 변경)
  pretrained: true                              # 사전학습 가중치 사용
  drop_rate: 0.1                                # 드롭아웃 비율
  drop_path_rate: 0.1                           # 드롭패스 비율 (Stochastic Depth)
  pooling: avg                                  # 풀링 방식 (평균 풀링)

# ------------------------------- 출력 설정 ------------------------------- #
output:
  exp_dir: experiments/train                    # 실험 결과 저장 디렉토리
  logs_dir: logs/train                          # 로그 저장 디렉토리  
  save_best_only: true                          # 최고 성능 모델만 저장
  save_weights_only: true                       # 가중치만 저장 (용량 절약)
  monitor: macro_f1                             # 모니터링 지표 (매크로 F1)
  mode: max                                     # 최대값 추적

# ------------------------------- 검증 설정 ------------------------------- #
validation:
  val_size: 0.2                                 # 검증 데이터 비율
  stratify: true                                # 계층화 분할 사용
  shuffle: true                                 # 데이터 셔플 활성화

# ------------------------------- 기타 설정 ------------------------------- #
inference:
  tta: true                                     # 테스트 시간 증강 활성화
  tta_transforms: 3                             # TTA 변환 개수 (줄여서 빠르게)
