# ----------------------------- 프로젝트 기본 설정 ----------------------------- #
project:
  run_name: convnext_base_384_fold_1            # 실행명 (모델명 기반)
  seed: 42                                       # 랜덤 시드 (재현 가능한 실험)
  date_format: '%Y%m%d'                         # 날짜 포맷 (예: 20250906)
  time_format: '%H%M'                           # 시간 포맷 (예: 1430)
  num_workers: 8                                # 데이터 로더 워커 수 (메모리 최적화)
  device: cuda                                  # 학습 디바이스 (GPU 사용)
  verbose: true                                 # 상세 로그 출력 여부
  log_prefix: train_highperf_convnext_base_384_fold_1  # 로그 파일 접두사

# ------------------------------- 데이터 설정 ------------------------------- #
data:
  root: ./data                                  # 데이터 루트 디렉토리
  train_csv: ./data/raw/train.csv               # 학습 데이터 CSV 파일
  sample_csv: ./data/raw/sample_submission.csv  # 제출 샘플 CSV
  image_dir_train: ./data/raw/train             # 학습 이미지 디렉토리
  image_dir_test: ./data/raw/test               # 테스트 이미지 디렉토리
  image_ext: .jpg                               # 이미지 파일 확장자
  id_col: ID                                    # ID 컬럼명
  target_col: target                            # 타깃 컬럼명 (레이블)
  num_classes: 17                               # 분류 클래스 수
  folds: 1                                      # K-Fold 교차검증 폴드 수 (1: 단일 폴드 모드, 2+: K-Fold 교차검증)
  valid_fold: 0                                 # 검증 폴드 (단일 폴드 모드에서는 무시됨)
  stratify: true                                # 계층적 분할 사용

# ------------------------------- 학습 설정 ------------------------------- #
train:
  img_size: 384                                 # 입력 이미지 크기 (384x384, 메모리 최적화)
  batch_size: 16                                # 배치 크기 (안정성 우선: 32)
  use_advanced_augmentation: true               # 고급 증강 기법 사용 여부 (trainsform.py true: build_advanced_train_tfms / false: build_advanced_train_tfms)
  epochs: 100                                   # 학습 에포크 수 (과적합 방지를 위해 조정)
  lr: 0.00012802227271884058                    # 학습률 (더 보수적: 1e-4)
  weight_decay: 0.013163367232645818            # L2 정규화 계수 (과적합 방지 강화)
  optimizer: adamw                              # 옵티마이저 (AdamW)
  scheduler: cosine                             # 스케줄러 (코사인 감쇠)
  warmup_epochs: 10                             # Warmup 에포크 (더 긴 워밍업: 10)
  mixed_precision: true                         # 혼합 정밀도 학습 (메모리 효율성)
  max_grad_norm: 0.5                            # 그래디언트 클리핑 (더 보수적: 0.5)
  label_smoothing: 0.1                          # 레이블 스무딩 (과적합 방지 강화: 0.1)
  use_mixup: true                               # Mixup 데이터 증강 사용
  mixup_alpha: 0.8                              # Mixup 알파 (더 보수적: 0.8)
  hard_augmentation: true                       # 강한 데이터 증강 적용
  log_interval: 3                               # 로그 출력 간격 (스텝 단위)
  early_stopping_patience: 20                   # Early Stopping 인내심 (20 에포크)
  reduce_lr_patience: 10                        # 학습률 감소 인내심 (10 에포크)
  use_ema: true                                 # EMA (Exponential Moving Average) 사용
  ema_decay: 0.9999                             # EMA 감쇠율
  temperature_scaling: true                     # Temperature Scaling 사용 (추론 정확도 향상)
  dropout_rate: 0.2                             # 드롭아웃 비율 (과적합 방지)
  dropout: 0.10286340155629473                  # 추가 드롭아웃 설정

# ------------------------------- 모델 설정 ------------------------------- #
model:
  name: convnext_base_384                       # 모델 아키텍처
  pretrained: true                              # 사전학습 가중치 사용
  drop_rate: 0.1                                # 드롭아웃 비율
  drop_path_rate: 0.1                           # 드롭패스 비율 (Stochastic Depth)
  pooling: avg                                  # 전역 풀링 방식 (평균 풀링)

# ------------------------------- 출력 설정 ------------------------------- #
output:
  logs_dir: logs/train                          # 로그 파일 저장 디렉토리
  exp_dir: "experiments/train"                  # 실험 결과(모델/메트릭) 저장 루트
  snapshots: true                               # 설정 스냅샷 저장 여부

# ------------------------------- WandB 설정 ------------------------------- #
wandb:
  project_name: document-classification-team    # WandB 프로젝트명
  entity: null                                  # WandB 엔티티 (팀/사용자)
  experiment_name: convnext_base_384_fold_1-highperf   # 실험명
  tags:                                         # 실험 태그
  - convnext_base_384                           # Vit Large Patch 16 384 태그
  - high-performance                            # 고성능 태그
  - mixup                                       # Mixup 태그
  - hard-aug                                    # 강한 증강 태그

# ------------------------------- 추가 학습 설정 ------------------------------- #
training:
  batch_size: 32                                # 추가 배치 크기 설정 (메모리 최적화)
